feat: add method for decoding sealed results
fingerprintjs/fingerprint-pro-server-api-go-sdk pull request #51
Opened 2024-01-22 14:36 UTC by TheUnderScorer

2024-01-23 14:19 UTC, ilfa requested changes
We need to test more bad scenarios, you can just check code coverage for this file.
<img width="644" alt="image" src="https://github.com/fingerprintjs/fingerprint-pro-server-api-go-sdk/assets/1009415/dee39280-e9c8-4c58-8ee0-0ee1fd570644">

2024-01-23 14:19 UTC, ilfa commented on sdk/sealed/unseal_test.go
> +		{
Please add one more bad key with a wrong size

2024-01-23 14:19 UTC, ilfa commented on template/README.mustache
> +To learn more, refer to example located in [example/sealedResults.go](./example/sealedResults.go).
The example is not really big, let's add the minimum variant to the readme.

2024-01-23 14:44 UTC, ilfa commented
I forgot to mention.
We need documentation for the API too.

2024-01-24 10:35 UTC, TheUnderScorer commented on sdk/sealed/unseal_test.go
> +		{
Done!

2024-01-24 10:36 UTC, TheUnderScorer commented on example/sealedResults.go
> +	responseJsonData, err := json.MarshalIndent(unsealedResponse, "", "  ")
Done! I've extracted an utility function for printing event response using known structure

2024-01-25 15:38 UTC, ilfa commented
@TheUnderScorer I managed to broke it (panic) with next negative test:

```go
	t.Run("with empty data", func(t *testing.T) {
		sealedResult := []byte("")
		key := base64Decode("p2PA7MGy5tx56cnyJaFZMr96BCFwZeHjZV2EqMvTq53=")

		keys := []DecryptionKey{
			{
				Key:       key,
				Algorithm: AlgorithmAES256GCM,
			},
		}
		_, err := UnsealEventsResponse(sealedResult, keys)

		assert.Error(t, err, ErrInvalidHeader)
	})
```

2024-01-29 12:28 UTC, ilfa commented
@TheUnderScorer I found one more missing testcase:

```go
	t.Run("with bad nonce", func(t *testing.T) {
		sealedResult := []byte{0x9E, 0x85, 0xDC, 0xED, 0xAA, 0xBB, 0xCC}
		key := base64Decode("p2PA7MGy5tx56cnyJaFZMr96BCFwZeHjZV2EqMvTq53=")

		keys := []DecryptionKey{
			{
				Key:       key,
				Algorithm: AlgorithmAES256GCM,
			},
		}
		_, err := UnsealEventsResponse(sealedResult, keys)

		assert.Error(t, err)
		assert.IsType(t, err, &AggregatedUnsealError{})

		var aggregateError *AggregatedUnsealError
		errors.As(err, &aggregateError)

		assert.Len(t, aggregateError.UnsealErrors, 1)

		unsealError := aggregateError.UnsealErrors[0]
		assert.ErrorContains(t, unsealError.Error, "nonce")
	})
```

2024-01-30 09:48 UTC, ilfa approved these changes

2024-01-30 10:27 UTC, merged

2024-01-31 12:53 UTC, ilfa commented
:tada: This PR is included in version 4.1.0 :tada:

The release is available on [GitHub release](https://github.com/fingerprintjs/fingerprint-pro-server-api-go-sdk/releases/tag/v4.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: